apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-chat-server
  namespace: quick-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quick-chat-server
  template:
    metadata:
      labels:
        app: quick-chat-server
    spec:
      containers:
        - name: server
          image: suraim001/quick-chat-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: quick-chat-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: quick-chat-config
                  key: PORT
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: quick-chat-config
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: quick-chat-secrets
                  key: JWT_SECRET
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: quick-chat-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: quick-chat-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: quick-chat-secrets
                  key: CLOUDINARY_API_SECRET
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15