apiVersion: v1
kind: ConfigMap
metadata:
  name: quick-chat-config
  namespace: quick-chat
data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGODB_URI: "mongodb://quick-chat-mongo:27017"
  BACKEND_URL: "http://localhost:30050"
