apiVersion: v1
kind: Secret
metadata:
  name: quick-chat-secrets
  namespace: quick-chat
type: Opaque
stringData:
  JWT_SECRET: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc5MDYyNTIwMCwiaWF0IjoxNzkwNjI1MjAwfQ.4rXZ34ccsvtuWEBfiVw2uMDkTDVZ6nnkeQIHiVeES-k"
  CLOUDINARY_CLOUD_NAME: "jk4exrni"
  CLOUDINARY_API_KEY: "879125687663421"
  CLOUDINARY_API_SECRET: "VU0KBhDws7VMyqk9rdGuMGZzFJE"
